spring:
  application:
    instance-id: ${HOSTNAME:LOCAL}
    name: yurim-logging-example

logging:
  file:
    path: ./logs/${spring.application.instance-id}
  config: classpath:logback-spring.xml

yurim:
  proj:
    service-code: logging-service
    domain: logging-example
